### ISSUE TITLE
Marks files ignored based on a line that was a comment

### ISSUE THREAD

**Issue by Aigeec** [bcoe/dotgitignore#1]
Example if a .gitignore read as follows:

```
# project-folder-name
coverage
```

I would expect only the coverage folder to be ignored. How ever any files with the `project-folder-name` in their path i.e. all files are considered shouldIgnore.

If you take a look at [minimatch](https://www.npmjs.com/package/minimatch) you will see that the makeRe method and the Minimatch constructor do not take the same options.

The [below code](https://github.com/bcoe/dotgitignore/blob/0fecf075e0d8ffe473e7fb7aaecd491c5713d870/lib/dotignore.js#L24) attempts to pass the properties for the [Minimatch class](https://www.npmjs.com/package/minimatch#minimatch-class) to the [makeRe method](https://www.npmjs.com/package/minimatch#methods)

```javascript
var match = minimatch.makeRe(line, {
      comment: commentLine,
      empty: emptyLine,
      matchBase: !rootedLine,
      negated: true // negated
    })
````
The properties are ignored and the match is made. I noticed this is the [standard-version](https://github.com/conventional-changelog/standard-version) module.

**Comment by ericksoen** [comment]
@Aigeec Thanks for working on this. I ran into the same issue on one of my projects and came to the same [conclusion you did](https://github.com/bmeck/dotignore/issues/8).

**Comment by jimlindeman** [comment]
Had issue where the .gitignore had
```
# ignore build directory
build
```
which then triggered false positive on everything in the Travis build base path: /home/travis/build/git-project/git-repo when standard-version was trying to identify the package.json.

So we need this logic to determine its working directory and only apply the .gitignore filters for folders underneath that.

**Comment by bcoe** [comment]
@jimlindeman mind opening a new issue? I believe this is a different problem related to the check being too permissive.
