### ISSUE TITLE
Negated or Rooted lines do not work

### ISSUE THREAD

**Issue by Aigeec** [bcoe/dotgitignore#2]
https://github.com/bcoe/dotgitignore/blob/0fecf075e0d8ffe473e7fb7aaecd491c5713d870/lib/dotignore.js#L22

Negated and Rooted lines are added to the end of the array but when matching it expects them to be in the same position as the matcher that is being checked against.

**Comment by bcoe** [comment]
I believe this should now be addressed as well \o/
